version: 2
updates:
  - package-ecosystem: "pip" # Tell Dependabot to check Python packages
    directory: "/" # Location of your requirements.txt (root directory)
    schedule:
      interval: "daily" # How often to check for updates 