"""Check models after cleanup

Revision ID: 1cbd1e99dfc0
Revises: 85ac18e38f27
Create Date: 2025-04-19 14:52:25.654761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cbd1e99dfc0'
down_revision = '85ac18e38f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('stock_price_cache') -> Commenting out due to potential permission errors or if table doesn't exist
    pass # Keep pass if no other operations are needed in upgrade
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price_cache',
    sa.Column('ticker', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('interval', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'start_date', 'end_date', 'interval', name='stock_price_cache_pkey')
    )
    # ### end Alembic commands ###
