"""Initial migration

Revision ID: 54da1785c634
Revises: 
Create Date: 2025-04-19 14:02:23.489735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54da1785c634'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Commenting out drop_table operation due to insufficient privileges
    # op.drop_table('stock_price_cache')
    with op.batch_alter_table('portfolio_cache', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_cache', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    # Commenting out create_table operation due to insufficient privileges
    # op.create_table('stock_price_cache',
    # sa.Column('ticker', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('start_date', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('end_date', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('interval', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('ticker', 'start_date', 'end_date', 'interval', name='stock_price_cache_pkey')
    # )
    # ### end Alembic commands ###
